apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: frontend
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend-canary
#spec:
#  ports:
#    - name: http
#      targetPort: 8080
#      port: 80
#  selector:
#    app: frontend
#
#
