kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: frontend-smoke-test
spec:
  metrics:
    - name: frontend-smoke-test
      interval: 5s
      count: 5
      failureLimit: 0
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: frontend-smoke-test
                    image: curlimages/curl:latest
                    command:
                      - /bin/sh
                      - -c
                      - |
                        (curl --insecure -L -o /dev/null -s -w %{http_code} \
                        http://frontend | grep ${HTTP_SUCCESS_CODE}) || (echo "http test failed. expected ${HTTP_SUCCESS_CODE}"; exit 1)
                    imagePullPolicy: IfNotPresent
                    env:
                      - name: HTTP_SUCCESS_CODE
                        value: "200"
                restartPolicy: Never
            backoffLimit: 1
