apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: backend-canary
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: frontend-canary
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: frontend
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: backend-smoke-test
spec:
  metrics:
    - count: 5
      failureLimit: 0
      interval: 5s
      name: backend-smoke-test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - |
                        (curl --insecure -L -o /dev/null -s -w %{http_code} \
                        http://backend-canary/version | grep ${HTTP_SUCCESS_CODE}) || (echo "http test failed. expected ${HTTP_SUCCESS_CODE}"; exit 1)
                    env:
                      - name: HTTP_SUCCESS_CODE
                        value: "200"
                    image: curlimages/curl:latest
                    imagePullPolicy: IfNotPresent
                    name: backend-smoke-test
                restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: frontend-smoke-test
spec:
  metrics:
    - count: 5
      failureLimit: 0
      interval: 5s
      name: frontend-smoke-test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - |
                        (curl --insecure -L -o /dev/null -s -w %{http_code} \
                        http://frontend-canary | grep ${HTTP_SUCCESS_CODE}) || (echo "http test failed. expected ${HTTP_SUCCESS_CODE}"; exit 1)
                    env:
                      - name: HTTP_SUCCESS_CODE
                        value: "200"
                    image: curlimages/curl:latest
                    imagePullPolicy: IfNotPresent
                    name: frontend-smoke-test
                restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/version: 1.118.1
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
    version: 1.118.1
  name: backend
spec:
  analysis:
    successfulRunHistoryLimit: 1
    unsuccessfulRunHistoryLimit: 1
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    canary:
      canaryMetadata:
        labels:
          version: canary
      canaryService: backend-canary
      stableMetadata:
        labels:
          version: stable
      stableService: backend
      steps:
        - setWeight: 25
        - pause:
            duration: 30
        - analysis:
            templates:
              - templateName: backend-smoke-test
        - pause: {}
  template:
    metadata:
      labels:
        app: backend
        sidecar.istio.io/inject: "true"
        version: 1.118.1
    spec:
      containers:
        - image: ghcr.io/procinger/argo-git-promoter-demo-backend:1.118.1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -f /proc/$(pidof backend)/exe
          name: backend
          ports:
            - containerPort: 8081
              name: http
          readinessProbe:
            httpGet:
              path: /version
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/version: 1.118.1
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
    version: 1.118.1
  name: frontend
spec:
  analysis:
    successfulRunHistoryLimit: 1
    unsuccessfulRunHistoryLimit: 1
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      canaryMetadata:
        labels:
          version: canary
      canaryService: frontend-canary
      stableMetadata:
        labels:
          version: stable
      stableService: frontend
      steps:
        - setWeight: 25
        - pause:
            duration: 30
        - analysis:
            templates:
              - templateName: frontend-smoke-test
        - pause: {}
  template:
    metadata:
      labels:
        app: frontend
        sidecar.istio.io/inject: "true"
        version: 1.118.1
    spec:
      containers:
        - env:
            - name: BACKEND_URL
              value: http://backend
          image: ghcr.io/procinger/argo-git-promoter-demo-frontend:1.118.1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - test -f /proc/$(pidof frontend)/exe
          name: frontend
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: frontend-ingress
spec:
  gateways:
    - istio-gateway/non-tls-gateway
  hosts:
    - argo-demo.kubedev.net
  http:
    - headers:
        request:
          add:
            x-canary: "true"
      match:
        - headers:
            cookie:
              regex: .*canary=true.*
      route:
        - destination:
            host: frontend-canary
            port:
              number: 80
          weight: 0
    - route:
        - destination:
            host: frontend
            port:
              number: 80
          weight: 100
