apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: gitops-promoter-demo
spec:
  ports:
    - name: gitops-promoter-demo
      port: 80
  selector:
    app: gitops-promoter-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-promoter-demo
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: gitops-promoter-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-promoter-demo
  template:
    metadata:
      labels:
        app: gitops-promoter-demo
    spec:
      containers:
        - env:
            - name: FOO
              value: BAZ
          image: ghcr.io/procinger/argo-git-promoter-demo:1.21.1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '[ -f /run/nginx.pid ] && test -f /proc/$(cat /run/nginx.pid)/exe'
          name: gitops-promoter-demo
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
