apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: gitops-promoter-demo
spec:
  ports:
    - name: gitops-promoter-demo
      port: 80
  selector:
    app: gitops-promoter-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-promoter-demo
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: gitops-promoter-demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gitops-promoter-demo
  template:
    metadata:
      labels:
        app: gitops-promoter-demo
    spec:
      containers:
        - image: ghcr.io/procinger/argo-git-promoter-demo:1.39.1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '[ -f /run/nginx.pid ] && test -f /proc/$(cat /run/nginx.pid)/exe'
          name: gitops-promoter-demo
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    argocd.argoproj.io/instance: argo-git-promoter-demo-prod
  name: http-smoke-test
spec:
  metrics:
    - count: 5
      failureLimit: 0
      interval: 5s
      name: http-smoke-test
      provider:
        job:
          metadata:
            annotations:
              argocd.argoproj.io/sync-options: Force=true,Replace=true
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - |
                        sleep 10 && (curl --insecure -H "canary: true" -L -o /dev/null -s -w %{http_code} \
                        http://gitops-promoter-demo | grep ${HTTP_SUCCESS_CODE}) || (echo "http test failed. expected ${HTTP_SUCCESS_CODE}"; exit 1)
                    env:
                      - name: HTTP_SUCCESS_CODE
                        value: "200"
                    image: curlimages/curl:latest
                    imagePullPolicy: IfNotPresent
                    name: http-smoke-test
                restartPolicy: Never
