apiVersion: v1
kind: Service
metadata:
  name: backend-stable
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: backend
