### backend
docker_build(
  'localhost:5001/backend',
  context='.',
  dockerfile='Dockerfile',
  target='backend',
)
k8s_yaml('k8s/backend.yaml')
k8s_resource('backend', port_forwards=8081)

### frontend
docker_build(
  'localhost:5001/frontend',
  context='.',
  dockerfile='Dockerfile',
  target='frontend',
)
k8s_yaml('k8s/frontend.yaml')
k8s_resource('frontend', port_forwards=8080)
