apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    version: "1"
    app.kubernetes.io/version: "1"
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: localhost:5001/backend
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "test -f /proc/$(pidof backend)/exe"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /version
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: backend

