apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/
  - frontend/
  - virtualservice.yaml

replacements:
  - source:
      name: backend
      kind: Rollout
      fieldPath: spec.template.spec.containers.[name=backend].image
      options:
        delimiter: ':'
        index: 1
    targets:
      - select:
          name: backend
          kind: Rollout
        fieldPaths:
          - metadata.labels.version
          - spec.template.metadata.labels.version
          - metadata.labels.app\.kubernetes\.io/version

  - source:
      name: frontend
      kind: Rollout
      fieldPath: spec.template.spec.containers.[name=frontend].image
      options:
        delimiter: ':'
        index: 1
    targets:
      - select:
          name: frontend
          kind: Rollout
        fieldPaths:
          - metadata.labels.version
          - spec.template.metadata.labels.version
          - metadata.labels.app\.kubernetes\.io/version
