apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-pods
spec:
  namespaceSelector:
    matchNames:
      - argo-git-promoter-dev
  selector:
    matchLabels:
      istio: monitor
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: stats/prometheus