apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - istio-pod-monitor.yaml

patches:
  - path: patches/patch-virtualservice.yaml
    target:
      group: networking.istio.io
      kind: VirtualService
      name: frontend-ingress
