name: Build and Push Images
on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Version
      run: echo 1.${{ github.run_number }}.${{ github.run_attempt }} > demo-app/version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to in-cluster Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v6.9.0
      with:
        context: demo-app
        file: demo-app/Dockerfile
        tags: |
          ghcr.io/procinger/argo-git-promoter-demo-backend:latest
          ghcr.io/procinger/argo-git-promoter-demo-backend:1.${{ github.run_number }}.${{ github.run_attempt }}
        cache-from: type=registry,ref=ghcr.io/procinger/argo-git-promoter-demo-backend:latest
        cache-to: type=inline
        target: backend
        platforms: linux/amd64,linux/arm64
        push: true

    - name: Build and push frontend
      uses: docker/build-push-action@v6.9.0
      with:
        context: demo-app
        file: demo-app/Dockerfile
        tags: |
          ghcr.io/procinger/argo-git-promoter-demo-frontend:latest
          ghcr.io/procinger/argo-git-promoter-demo-frontend:1.${{ github.run_number }}.${{ github.run_attempt }}
        cache-from: type=registry,ref=ghcr.io/procinger/argo-git-promoter-demo-frontend:latest
        cache-to: type=inline
        target: frontend
        platforms: linux/amd64,linux/arm64
        push: true
